### ISSUE TITLE
Nested function error

### ISSUE THREAD

**Issue by ariebrainware** [ariebrainware/javascript-challenge1#1]
https://github.com/ariebrainware/javascript-challenge1/blob/5daae9698d76a0bdc41bb463ae72531eaf6584e1/index.js#L176-L189

**Comment by michaeltamsil** [comment]
on line 191 it's says print of return from calc function.
on calc function there's no return ...(not include line 178 & 181 because it's return to `this.add` & `this.substract` function)
how about  on line 185 changed to `return.add();` also with 187 to `return this.substract();`

or the elegant way
`
let value = 0;
if (operator == "add") { 
     value = this.add(); 
   } else { 
     value = this.substract(); 
   } 
return value;
`

**Comment by ariebrainware** [comment]
Thanks.. its work
